"""Add event whatsapp link

Revision ID: b7c41e0d9a52
Revises: dfadf58f0fac
Create Date: 2026-09-13 09:00:00.000000

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "b7c41e0d9a52"
down_revision = "dfadf58f0fac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("whatsapp_link", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_column("whatsapp_link")

    # ### end Alembic commands ###
